version: "3.9"

services:
  db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: inventory_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend:/app

volumes:
  pgdata:
